import type { Metadata } from "next";
import Link from "next/link";
import LegalShell from "../legal-shell";

export const metadata: Metadata = { title: "Privacy Policy | OddsAura", description: "How OddsAura collects, uses and protects personal information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <LegalShell kicker="Your information" title="Privacy policy.">
    <section><h2>1. What this policy covers</h2><p>This policy explains how OddsAura (“we”, “us”) handles personal information when you visit the website, create an account, use predictions or bookmaker-code tools, save slips, or contact us. OddsAura is an independent football-analysis service and is not a bookmaker.</p></section>
    <section><h2>2. Information we collect</h2><ul><li><strong>Account data:</strong> your name, email address, password hash and account role.</li><li><strong>Product data:</strong> prompts, saved slips, booking codes, conversion requests, prediction preferences and generated results associated with your account.</li><li><strong>Technical and security data:</strong> IP address, browser or device information, session identifiers, request times and diagnostic or abuse-prevention logs.</li><li><strong>Messages:</strong> information you include when asking for support or exercising a privacy right.</li></ul><p>Do not send bookmaker passwords, payment-card details, national identification numbers or other unnecessary sensitive information through OddsAura.</p></section>
    <section><h2>3. Why we use it</h2><p>We use information to provide and secure accounts; answer requests; build, save and convert slips; maintain conversation context; prevent fraud and abuse; diagnose faults; improve accuracy and usability; comply with law; and respond to support or rights requests.</p><p>Depending on applicable law, this processing is based on performing our agreement with you, our legitimate interests in operating a safe and useful service, compliance with legal obligations, or your consent where consent is required.</p></section>
    <section><h2>4. Bookmakers and service providers</h2><p>When you ask OddsAura to read, create or convert a bookmaker code, the relevant code, fixture or selection information may be sent to that bookmaker’s public service. Do not provide your bookmaker login credentials. Bookmakers operate under their own privacy terms.</p><p>We may use hosting, database, email, analytics and security providers that process limited information for us under appropriate instructions. We do not sell personal information.</p></section>
    <section><h2>5. Cookies and sessions</h2><p>OddsAura uses essential cookies or similar storage to keep you signed in, protect sessions and remember required product state. These are necessary for requested features. We do not currently use advertising cookies. If that changes, this policy and any consent controls will be updated first.</p></section>
    <section><h2>6. Retention and deletion</h2><p>We keep account and saved-product data while your account is active and for a reasonable period afterwards where needed for security, legal obligations or dispute resolution. Password-reset tokens expire after 30 minutes. Security logs are retained only as long as reasonably necessary for protection and troubleshooting.</p><p>You may request account or personal-data deletion through the Contact page. Some minimal records may be retained where the law requires it or where necessary to establish, exercise or defend legal claims.</p></section>
    <section><h2>7. Security and international processing</h2><p>We use access controls, encrypted connections, hashed passwords, secure session cookies, input validation and rate limits. No online system is completely risk-free. Service providers may process information in other countries, subject to protections required by applicable law.</p></section>
    <section><h2>8. Your choices and rights</h2><p>Depending on where you live, you may ask to access, correct, delete, restrict or export your personal information, object to certain processing, or withdraw consent. You may also complain to your local data-protection authority. We may need to verify your identity before completing a request.</p></section>
    <section><h2>9. Age restriction and changes</h2><p>OddsAura is for adults aged 18 or older. We do not knowingly collect account information from children. We may update this policy when the product, providers or law changes; material updates will be dated and, where appropriate, shown in the product.</p></section>
    <section><h2>10. Contact</h2><p>Use the <Link href="/contact">Contact page</Link> for privacy questions, data requests or account deletion. For privacy requests by email, write to <a href="mailto:privacy@oddsaura.site">privacy@oddsaura.site</a>.</p></section>
  </LegalShell>;
}
