import Link from "next/link";
import Brand from "./brand";
import "./landing.css";

export default function LandingPage() {
  return <main className="landing">
    <nav className="landing-nav landing-shell"><Brand /><div className="landing-links"><Link className="landing-login" href="/login">Log in</Link><Link className="landing-signup" href="/signup">Create free account</Link></div></nav>
    <section className="landing-hero landing-shell">
      <div className="landing-hero-copy"><span className="landing-kicker">Probability-led football predictions</span><h1>Smarter picks.<br /><i>Ready-to-use codes.</i></h1><p>OddsAura analyses football form, goals, probabilities and market value—then turns qualified predictions into tickets you can review, save and convert to SportyBet booking codes.</p><div className="landing-actions"><Link className="primary" href="/signup">Start free <span>↗</span></Link><Link className="secondary" href="/login">I already have an account</Link></div><div className="landing-proof"><span>No paid football API required</span><span>18+ responsible betting tools</span></div></div>
      <div className="landing-preview" aria-label="OddsAura ticket preview"><div className="preview-head"><Brand compact /><span>Probability board</span></div><div className="preview-ticket"><span>Balanced ticket · Preview</span><h2>Today&apos;s qualified picks</h2><div className="preview-game"><div><strong>Arsenal vs Brighton</strong><span>Over 1.5 goals · 81% confidence</span></div><strong>1.28</strong></div><div className="preview-game"><div><strong>Real Madrid vs Sevilla</strong><span>Home win · 77% confidence</span></div><strong>1.36</strong></div><div className="preview-game"><div><strong>Inter vs Atalanta</strong><span>Double chance · 79% confidence</span></div><strong>1.24</strong></div></div><div className="preview-score"><span>Model score</span><strong>81%</strong><small>↑ 4.6%</small></div><div className="preview-code"><span>SportyBet code preview</span><strong>••••••</strong></div></div>
    </section>
    <section className="landing-metrics"><div className="landing-shell"><article><p>Built for clearer decisions—not empty promises or blind selections.</p></article><article><strong>2–21 legs</strong><span>Flexible ticket sizes</span></article><article><strong>30+ markets</strong><span>Prediction coverage</span></article><article><strong>One account</strong><span>Slips, codes and results</span></article></div></section>
    <section className="landing-section landing-shell" id="how-it-works"><div className="landing-section-head"><h2>From match data<br /><i>to one clean slip.</i></h2><p>The engine scores each available market using recent home and away performance, goal trends, opposition strength, head-to-head context, implied probability and available price value.</p></div><div className="landing-steps"><article><span>01</span><h3>Collect matches</h3><p>Upcoming fixtures, results, team form, goals, leagues and available prices are refreshed automatically.</p></article><article><span>02</span><h3>Score the markets</h3><p>Every supported market receives a probability and confidence score. Weak or unsupported signals are rejected.</p></article><article><span>03</span><h3>Choose your picks</h3><p>Select from qualified predictions or use the automatic 2, 5, 10 and 21-leg ticket categories.</p></article><article><span>04</span><h3>Create and track</h3><p>Generate a SportyBet code, save the slip, share its JPEG and follow the result from your account.</p></article></div></section>
    <section className="landing-section landing-feature-band"><div className="landing-shell"><div className="landing-section-head"><h2>Everything stays<br /><i>in one account.</i></h2><p>Your prediction workspace follows you across devices while active codes and personal ticket history remain private.</p></div><div className="landing-features"><article><h3>Broader market coverage</h3><p>1UP, 2UP, match results, double chance, totals, GG/NG, team goals, draw no bet and more.</p></article><article><h3>Honest code matching</h3><p>SportyBet-listed legs generate automatically. Missing fixtures are identified clearly instead of silently failing.</p></article><article><h3>Results and winnings</h3><p>Track pending, won, lost and void selections with stake, potential return and actual-return calculations.</p></article></div></div></section>
    <section className="landing-cta landing-shell"><div className="landing-cta-inner"><div><h2>Build your first<br />OddsAura slip.</h2><p>Create a free account to unlock predictions and booking codes.</p></div><Link href="/signup">Create free account ↗</Link></div></section>
    <footer className="landing-footer landing-shell"><strong>OddsAura</strong><p>Predictions are information, not guarantees. Please bet responsibly.</p><nav><a href="#how-it-works">How it works</a><Link href="/login">Log in</Link></nav></footer>
  </main>;
}
