"use client";

import { useEffect, useState } from "react";
import "./product.css";

type Selection = { id: string; oddsSnapshot: number; prediction: { selection: string; confidenceScore: number; fixture: { kickoff: string; homeTeam: { name: string }; awayTeam: { name: string }; league: { name: string } } } };
type Ticket = { id: string; title: string; category: string; totalOdds: number; confidence: number; bookingCodes: Array<{ id: string; provider: string; code: string; deepLink?: string }>; selections: Selection[] };

const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3000";

export default function Home() {
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState("");

  useEffect(() => {
    fetch(`${apiUrl}/api/tickets`)
      .then((response) => response.ok ? response.json() : Promise.reject(new Error("Could not load today’s tickets")))
      .then((data) => setTickets(data.tickets ?? []))
      .catch((reason) => setError(reason.message))
      .finally(() => setLoading(false));
  }, []);

  async function copyCode(code: string) {
    await navigator.clipboard.writeText(code);
    setCopied(code);
    setTimeout(() => setCopied(""), 1800);
  }

  return <main className="oa-app">
    <header className="oa-header">
      <a className="oa-brand" href="/" aria-label="OddsAura home"><span className="oa-mark">↗</span><span>Odds<i>Aura</i></span></a>
      <div className="oa-status"><span /> Probability engine online</div>
      <a className="oa-admin-link" href="/admin">Admin</a>
    </header>

    <section className="oa-intro">
      <div><span className="oa-kicker">Today’s probability board</span><h1>Football picks,<br /><i>scored by data.</i></h1></div>
      <p>Form, goals, venue performance, head-to-head and bookmaker value—combined into clear tickets you can verify before you play.</p>
    </section>

    <nav className="oa-filters" aria-label="Ticket categories"><a href="#safe">Safe 2–3 Odds</a><a href="#balanced">Balanced 5–10 Odds</a><a href="#high-risk">High Risk</a></nav>

    {loading && <div className="oa-empty">Loading today’s tickets…</div>}
    {!loading && error && <div className="oa-empty"><strong>The backend is not connected yet.</strong><span>{error}</span></div>}
    {!loading && !error && tickets.length === 0 && <div className="oa-empty"><strong>No published tickets yet.</strong><span>Tickets generated by the engine will appear here after admin review.</span></div>}

    <section className="oa-ticket-grid">
      {tickets.map((ticket) => <article id={ticket.category.toLowerCase().replace("_", "-")} className="oa-ticket" key={ticket.id}>
        <div className="oa-ticket-head"><div><span>{ticket.category.replace("_", " ")}</span><h2>{ticket.title}</h2></div><strong>{ticket.totalOdds.toFixed(2)}<small>Total odds</small></strong></div>
        <div className="oa-selections">{ticket.selections.map((item) => <div className="oa-selection" key={item.id}><div><span>{item.prediction.fixture.league.name} · {new Date(item.prediction.fixture.kickoff).toLocaleString()}</span><h3>{item.prediction.fixture.homeTeam.name} vs {item.prediction.fixture.awayTeam.name}</h3><p>{item.prediction.selection}</p></div><div className="oa-numbers"><strong>{item.oddsSnapshot.toFixed(2)}</strong><span>{Math.round(item.prediction.confidenceScore * 100)}%</span></div></div>)}</div>
        <div className="oa-ticket-foot"><div><span>Average confidence</span><strong>{Math.round(ticket.confidence * 100)}%</strong></div>{ticket.bookingCodes.length ? <div className="oa-codes">{ticket.bookingCodes.map((booking) => <button type="button" key={booking.id} onClick={() => copyCode(booking.code)}><span>{booking.provider}</span><strong>{copied === booking.code ? "Copied" : booking.code}</strong></button>)}</div> : <span className="oa-awaiting">Booking code awaiting admin review</span>}</div>
      </article>)}
    </section>

    <footer className="oa-footer"><span>OddsAura</span><p>18+ · Predictions are information, not guarantees. Please bet responsibly.</p></footer>
  </main>;
}
