import type { Metadata } from "next";
import Link from "next/link";
import LegalShell from "../legal-shell";

export const metadata: Metadata = { title: "Terms of Use | OddsAura", description: "The terms that apply when using OddsAura.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <LegalShell kicker="Using OddsAura" title="Terms of use.">
    <section><h2>1. Agreement and eligibility</h2><p>By using OddsAura, you agree to these Terms and the Privacy Policy. You must be at least 18, legally permitted to use betting-related information where you live, and able to enter this agreement. Stop using the service if you do not agree.</p></section>
    <section><h2>2. What OddsAura provides</h2><p>OddsAura provides football information, probability-led predictions, slip analysis, booking-code creation and code-conversion tools. OddsAura is not a bookmaker, does not accept stakes, hold betting funds, place bets for you or control bookmaker settlement.</p><p className="legal-callout">Predictions are opinions based on available data, not promises. Odds, fixtures, markets and booking codes can change or become unavailable. Always review the final bookmaker slip before placing a bet.</p></section>
    <section><h2>3. Accounts</h2><p>You must provide accurate information, protect your password and tell us promptly if you suspect unauthorized access. You are responsible for activity performed through your account. We may restrict or close accounts used unlawfully, abusively, automatically at harmful scale, or in ways that threaten the service or other users.</p></section>
    <section><h2>4. Predictions, codes and conversions</h2><ul><li>A generated code is valid only if the named bookmaker accepts and reloads it with the displayed selections.</li><li>A conversion may omit a match or market that the destination bookmaker does not list. OddsAura will identify excluded selections where the bookmaker supplies enough information.</li><li>Bookmaker odds and rules control the final bet. OddsAura’s displayed combined odds may differ from the bookmaker’s current total.</li><li>You are responsible for checking teams, markets, kick-off times, odds, stake and potential return before confirming anything.</li></ul></section>
    <section><h2>5. Acceptable use</h2><p>Do not misuse the service, bypass access controls or rate limits, scrape at harmful scale, probe security, upload malicious content, impersonate others, infringe rights, manipulate product data, or use OddsAura for unlawful activity. Do not submit third-party account credentials or confidential payment information.</p></section>
    <section><h2>6. Intellectual property and user content</h2><p>OddsAura’s software, design, branding and original content are protected by applicable intellectual-property law. You keep rights in content you submit and give us the limited permission needed to process it and provide requested features. Bookmaker names and trademarks belong to their respective owners; their appearance does not imply endorsement.</p></section>
    <section><h2>7. Third-party services</h2><p>Bookmakers and other linked services are independent. Their availability, prices, rules, privacy practices, settlements and account decisions are outside our control. Your use of them is governed by their own terms.</p></section>
    <section><h2>8. Availability and liability</h2><p>We aim to keep OddsAura accurate and available, but the service may be interrupted, delayed or incorrect. To the fullest extent permitted by law, OddsAura is provided “as is” without a guarantee of profit, availability or fitness for a particular betting decision. Nothing in these Terms excludes liability that cannot legally be excluded. You remain responsible for your betting decisions and losses.</p></section>
    <section><h2>9. Changes and ending use</h2><p>We may improve, suspend or withdraw features and may update these Terms. Material changes will be dated and, where appropriate, communicated in the product. You may stop using OddsAura at any time and request account deletion through Contact.</p></section>
    <section><h2>10. Contact and disputes</h2><p>Please contact us first so we can try to resolve a concern. These Terms are governed by applicable law, and disputes may be brought before a court or authority with lawful jurisdiction. Visit <Link href="/contact">Contact</Link> or email <a href="mailto:support@oddsaura.site">support@oddsaura.site</a>.</p></section>
  </LegalShell>;
}
